fastTSNE/nearest_neighbors.py, fastTSNE/pynndescent/pynndescent_.py, fastTSNE/tsne.py, tests/test_tsne.py
- As per #10, it is vital for tSNE optimization that the initialization has small variance. Without this scaling, PCA initialization can potentially lead to really bad results.
- Remove `pca` option when embedding new points into an existing embedding. This makes no sense because likely the points in the original space would have moved significantly and adding new points would be meaningless.
=> Ensure PCA initialization has small variance

fastTSNE/tsne.py
In case a callback was provided that was a simple function, then we would crash because functions have no `optimzation_about_to_start` property.
=> Fix callback crash if callback was a function

fastTSNE/tsne.py
We can simplify the KL divergence correction for early exaggeration. See discussion in https://github.com/KlugerLab/FIt-SNE/issues/37.
=> Simplify KL divergence correction

setup.py
The module was not being properly compiled on Windows, the `openmp` and `O3` flags aren't' the same on Windows. This resulted in the library being slower on Windows than scikit-learn (see #8)!
=> Fix compilation flags on Windows

fastTSNE/affinity.py, fastTSNE/nearest_neighbors.py, fastTSNE/tsne.py, tests/test_tsne.py
Distance metrics had undefined behaviour i.e. it was up to the library to raise errors and handle everything.
- Use only distance metrics available in both nearest neighbour libraries and exclude the others. If it's not a valid distance metric, then an appropriate error is raised.
- Use ball tree instead of KD tree because it supports many more distance metrics.
=> Properly handle distance metrics

fastTSNE/affinity.py, tests/test_affinities.py
Following the art of using t-SNE, good results can be obtained by first running t-SNE at a high perplexity to capture global structure, then decreasing to account for more local structure.
Add `set_perplexity` method to `PerplexityBasedNN`. This allows lowering the perplexity without having to first recompute all the nearest neighbors. Proper bandwidths for the Gaussians still need to be recomputed in order to form a new affinity matrix.
=> Allow decreasing perpleixties in perplexity based affinities

fastTSNE/nearest_neighbors.py
pynndescent params were chosen completely arbitrarily.
Use defaults from UMAP, they appear to have some hacky values, but they are certainly more informed than the current defaults.
=> Change pynndescent params to UMAP defaults

setup.py
The library can't be properly compiled on Macs because the default compiler `clang` doesn't support `openMP`.
Disable openMP for the time being.
=> Remove openmp flag for mac sytems

fastTSNE/affinity.py
For some reason, the affinity matrix in for fixed sigmas wasn't normalized properly.
Properly normalize.
=> Fix wrong normalization for affinities in fixed sigma affinities

fastTSNE/affinity.py, fastTSNE/nearest_neighbors.py, tests/test_nearest_neighbors.py, tests/test_tsne.py
Using only shared distance metrics is silly. We remove a lot of them just because the C++ implementation of VPTrees only support euclidean.
All metrics supported by each KNNIndex class are supported.
=> Use all available distance metrics for nearest neighbors

openTSNE/nearest_neighbors.py
When using `pynndescent` for approximate NN search, the index was built, then queried with the training data. Little did I know that I could get the nearest neighbors out of the index as soon as it was built.
Properly use pynndescent when querying nearest neighbors for training data.
=> Properly call pynndescent for querying training data

openTSNE/nearest_neighbors.py
As it turns out, pynndescent appears *faster* when training on the whole data set with the default 15 neighbors, then querying with the remaining e.g. 90 neighbors for perplexity=30.
Further testing needed, but for the time being, the previous method was faster.
=> Revert nn descent search

README.md, docs/source/api/index.rst, docs/source/api/sklearn.rst, openTSNE/sklearn.py, openTSNE/tsne.py, tests/test_sklearn_wrapper.py
While the API is fairly similar to scikit-learn, it's still annoying to switch out different methods due to openTSNE returning the embedding from `fit` and scikit-learn returning the fitter object. This means that when I want to switch out MDS for t-SNE, I not only need to change the object but also the method from `fit_transform` to `fit`.
Implement scikit-learn API.
=> Add scikit-learn API

.travis.yml, appveyor.yml, benchmarks/benchmark.py, benchmarks/macosko.py, openTSNE/_matrix_mul/matrix_mul.pxd, openTSNE/_matrix_mul/matrix_mul_fftw3.c, openTSNE/_matrix_mul/matrix_mul_fftw3.pyx, openTSNE/_matrix_mul/matrix_mul_numpy.c, openTSNE/_matrix_mul/matrix_mul_numpy.pyx, openTSNE/_tsne.c, openTSNE/_tsne.pyx, openTSNE/affinity.py, openTSNE/callbacks.py, openTSNE/initialization.py, openTSNE/kl_divergence.c, openTSNE/kl_divergence.pyx, openTSNE/metrics.py, openTSNE/nearest_neighbors.py, openTSNE/quad_tree.c, openTSNE/quad_tree.pyx, openTSNE/tsne.py, setup.py, tests/test_correctness.py, tests/test_nearest_neighbors.py, tests/test_tsne.py
- use -march=native flag
- clean up setup.py and remove dirty call to `pip install numpy`
- change default `min_num_intervals` to 50
- change transform api so it includes early exaggeration
- drop support for 32 bit systems (conda-forge did this several months ago)
- add CI for Python 3.7
=> Various improvements

openTSNE/initialization.py, openTSNE/tsne.py
#68: Add `svd_solver="auto"` to pca init
#69: No longer need to set `negative_gradient_method="fft"` when initializing `TSNEEmbedding`
=> Improvements

.travis.yml
The `setup_requires` directive in setuptools seemed promising as a way to bootstrap numpy before the compilation process. Unfortunately, this didn't work for some version mismatch reason ([stackoverflow question](https://stackoverflow.com/questions/56848016/setuptools-setup-requires-and-install-requires-behaves-differently))? So this idea was abandoned
Ensure numpy is installed on travis before setup takes place.
=> Ensure numpy is installed on travis

openTSNE/nearest_neighbors.py, tests/test_correctness.py, tests/test_nearest_neighbors.py
Exact nearest neighbor search provided by scikit-learn did not implement cosine distance, because I guess you can't really compute that using the tree-based methods and it would be computed using pdist.
We can exploit the fact that the distance rankings are the same for cosine distance as they are for euclidean distance on instance-normalized data. So we can find the nearest neighbors using the standard euclidean ball trees, then recompute the true cosine distance for only these neighbors.
=> Add cosine distance support to ball tree

openTSNE/tsne.py, tests/test_tsne.py
Pickling doesn't work for `TSNEEmbedding` objects. 
Fix picking. For some reason, things crash if I try to include the `optimizer` in the pickle, even though it's pickled fine on its own. So the optimizer is not included.
In general, this might not be a problem because the typical use case for pickling would be to create the embedding, then use if for subsequent transforms. It can even be optimized later on as well, but the momentum terms will be reset when unpickling.
=> Fix pickling for TSNEEmbedding objects; missing optimizer

appveyor.yml, setup.py
`pynndescent` is incompatible with the latest numpy release 1.17.0
Fix numpy version to 1.16.*
=> Fix numpy version to 1.16.*

openTSNE/tsne.py
Fixes #80
Remove constant factor from gradients. This deviates from the true gradient and the implementation in scikit-learn, but is now consistent with FIt-SNE and van der Maaten's implementation.
=> Remove constant 4 factor from gradients

azure-pipelines-release.yml
In #90, it was brought up that the current azure-pipelines setup somehow doesn't properly package the source distribution, and doesn't include *.pxd or *.c files, as well as ignores the fftw matrix_mul implementation.
Package sdist on a separate unix VM.
=> Build sdist on separate linux vm

openTSNE/affinity.py, openTSNE/nearest_neighbors.py, openTSNE/tsne.py, tests/test_nearest_neighbors.py
See #93  
Added the option for callable metrics to the `openTSNE.nearest_neighbors` module. `NNDescent` checks if metric is compiled with `numba`, gives an informative warning, and then attempts to automatically compile it. If the function is already compiled or `NNDescent` is not being used then the callable is passed without any further checks. Docstrings have also been updated to match other docstrings with multiple types. If you'd like unit tests for this, then please provide guidance on how best to do this.
=> Add support for callable metrics

openTSNE/initialization.py, openTSNE/tsne.py
Fixes #110.
I ended up implementing diffusion maps only because computationally, computing the leading eigenvectors is much faster than the smallest eigenvectors, and of the various spectral methods, diffusion maps are the only ones that require this. I checked what UMAP does - it uses the symmetric normalized laplacian for initialization - but they manually set the number of lanczos iteration limit, which I don't understand. This seemed like the better option.
@dkobak Do you want to take a look at this? I implemented this using `scipy.sparse.linalg.svds` because it turns out to be faster than `scipy.sparse.linalg.eigsh` and it seemed to produce strange results when I increased the error tolerance, while `svds` results seemed reasonable.
=> Add spectral initialization using diffusion maps

openTSNE/_tsne.c, openTSNE/_tsne.pxd, openTSNE/_tsne.pyx, openTSNE/kl_divergence.c, openTSNE/tsne.py
When calling transform, the previous implementation took the most straightforward approach and just recomputed everything on the reference as well as the new points. This is redundant since the reference embedding never changes.
Now, the reference embedding is padded equally on each side and the interpolation grid is computed once. Padding enables points that are not similar to the embedding to move away from the embedding. When new points are introduced, we can then quickly calculate their negative gradient from the precomputed interpolation grid. To prevent points from moving outside the interpolation grid, we enforce a circular boundary on the embedding. This massively speeds up the runtime of transform.
This only changes the FFT implementation. The same could be done for BH, but since …
=> transform: evaluate interpolation grid once

openTSNE/callbacks.py, openTSNE/utils.py
- Warning filters override filters from other packages (e.g. filter for OrangeDeprecationWarning was overridden - test started to fail)
- DeprecationWarning can be replaced with FutureWarning:
```
Base category for warnings about deprecated features when those warnings are intended for 
end-users of applications that are written in Python.
```
As far I understand DeprecationWarning is made for developers of the package (in your case openTSNE developers), while FutreWarning is for users of your package. FutreWarning is printed by default.
- Removed filters
- DeprecationWarning replaced with FutureWarning
=> [FIX] Removed warnings filters, DeprecationWarnings replaced with FutureWarning

openTSNE/tsne.py, tests/test_tsne.py
Fixes #132.
I tested it on MNIST with default parameters and the default `max_step_norm=5` (same as in FIt-SNE) does not affect the embedding (I think it's never triggered). If one sets it to a much smaller number, it produces a funny effect:
Here with `max_step_norm=0.01` no point can be further than 7.5 from zero (with 750 iterations).
@jnboehm tested it on one case where we had some points shooting off (with strong exaggeration factor), and the default `max_step_norm=5` resolved the problem.
For `transform()` I set the default to `None` because there you have nonzero `max_grad_norm` by default so I thought it might be enough. You are also limiting the interpolation grid there, I think.
=> max update norm parameter

openTSNE/nearest_neighbors.py, tests/test_nearest_neighbors.py
Fixes #130 .
Changes:
*    Query() is only used for k>15.
*    n_jobs fixed to 1 for sparse inputs to avoid a pynndescent bug
*    find all points where index contains -1 values, and let them randomly attract each other.
=> Workaround for -1 in pynndescent index

azure-pipelines-release.yml, azure-pipelines.yml, openTSNE/affinity.py, openTSNE/nearest_neighbors.py, setup.py, tests/test_nearest_neighbors.py
The kNN algorithms available in openTSNE are not as fast and/or memory efficient as HNSW (https://arxiv.org/abs/1603.09320).
Furthermore, Annoy, BallTree, and pynndescent are not made for high-dimensional data; For example, Annoy even throws an error above 1000 dimensions.
This pull request ...
* adds hnswlib as a dependency
* adds option to choose 'hnswlib' to `build_knn_index` for `Affinities`
* implements additional `KNNIndex` class to interface with hnswlib
If you like the idea of having HNSW as an alternative, I'll add tests and some documentation.
=> Add hnswlib as k nearest neighbour index

openTSNE/affinity.py, tests/test_affinities.py
This should implement my suggestion in #156.
I checked and it seems to work as expected. 
However, notice that I changed the logic in `to_new` and in `set_perplexity` a little, to make it consistent with `k_neighbors` that could possibly be user-provided. For simplicity, I made these functions always use the same originally provided or computed `k_neighbors` neighbors. So e.g. if the original affinity is computed with `perplexity=20, k_neighbors=25`, then `to_new(perplexity=10)` will use the same `k_neighbors=25`. Previously your code would have used 3*10=30 in this case (which won't work in this particular situation because 25<30).
The same for `set_perplexity`. 
This may result in some loss of efficiency, but I thought it's probably negligible. Let me know what you think.
=> Allow to set k_neighors in perplexity based affinity

openTSNE/affinity.py, openTSNE/nearest_neighbors.py, tests/test_nearest_neighbors.py, tests/test_tsne.py
#162
I initially thought we could get rid of all the cosine distance logic, but it turns out that scikit-learn doesn't implement it. So that workaround stays. Basically, this is just a copy of `BallTree`, but with `method="auto"`.
I've also deprecated `BallTree`, which will be removed in future versions. Then, we can also get rid of this code duplication.
=> Add sklearn nearest_neighbor search with method="auto"

openTSNE/tsne.py, openTSNE/utils.py, tests/test_utils.py
Apparently, there I had made a mistake in the previous "fix" of circular clipping. This here should really fix it once and for all.
- Fix gradient clipping
- I found another bug in 1d FFT gradients when using precomputed grids.
=> Fix circular clipping

openTSNE/affinity.py, openTSNE/tsne.py
Fixes #171.
Adds missing mentions of hnsw in relevant docstrings.
=> Add missing references to hnsw neighbors method

openTSNE/affinity.py, openTSNE/nearest_neighbors.py, openTSNE/tsne.py, tests/test_affinities.py, tests/test_correctness.py, tests/test_nearest_neighbors.py, tests/test_tsne.py
Fixes #170.
- Change API for `KNNIndex.__init__` and `KNNIndex.build` so that `data` and `k` are specified in the constructor. This makes more sense in light of the precomputed distance class. This is against what I usually say, that the API needs to be backwards compatible, but I strongly suspect this is so deep within the library that nobody has ever done anything with it. So I think it should be okay here.
- Change API for `TSNE.__init__` and `TSNE.fit`, removing the `affinities` parameter from the constructor. This lead to some very strange function calls. We now change `.fit` so that either a data matrix can be passed in, or an affinity object. Optionally, the user can specify the initialization as well. Same goes for `prepare_partial`. Again, this is such niche usage, I doubt anyone …
=> Support precomputed distance matrices

openTSNE/affinity.py, openTSNE/nearest_neighbors.py, openTSNE/tsne.py, tests/test_affinities.py, tests/test_different_usages.py, tests/test_tsne.py
Adding this kind of functionality complicated things quite a bit, so a pretty major refactor was necessary to keep things manageable. Notable changes include:
- `build_knn_index` no longer computes the neighbors, but only returns the correct index. This lets us pass in already existing `KNNIndex` objects to affinities.
- All `Affinity` classes can now be called in two ways. 1) with a data matrix, as is standard, or 2) using an existing `KNNIndex` object. This is in preparation for scanpy integration, where we will have to use existing KNNGs.
- `KNNIndex` objects now have the default parameter `metric="euclidean". This just makes it easier to debug or instantiate manually.
- Add `nearest_neighbors.PrecomputedNeighbors` which allows us to wrap the standard KNNG representations.
Because …
=> Refactor affinity module

azure-pipelines-release.yml, azure-pipelines.yml, openTSNE/nearest_neighbors.py
Fixes #211.
Remove the docstring altogether. The pickling behaviour now works exactly as expected.
=> nearest_neighbors: remove outdated annoy docstring on pickling

openTSNE/affinity.py, tests/test_affinities.py, tests/test_different_usages.py
Implements #216.
Allows to do the following:
```python
from openTSNE import TSNE
from openTSNE.affinity import PrecomputedAffinities
Z = TSNE().fit(affinities = PrecomputedAffinities(P))
```
=> Implement precomputed affinity class

openTSNE/tsne.py, tests/test_different_usages.py
Implements #218.
First, `early_exaggeration="auto"` is now set to `max(12, exaggeration)`.
Second, the learning rate. We have various functions that currently take `learning_rate="auto"` and set it to `max(200, N/12)`. I did not change this, because those functions usually do not know what the early exaggeration was. So I kept it as is. I only changed the behaviour of the base class: there `learning_rate="auto"` is now set to `max(200, N/early_exaggeration)`.
This works as intended:
```Python
X = np.random.randn(10000,10)
TSNE(verbose=True).fit(X)
TSNE(verbose=True, exaggeration=5).fit(X)
TSNE(verbose=True, exaggeration=20).fit(X)
```
(Note that the learning rate is currently not printed by the `repr(self)` because it's kept as "auto" at construction time and only set later. That's also …
=> Implement auto early exaggeration

openTSNE/tsne.py, tests/test_tsne.py
In some forms of usage, the initialization was changed, which is incorrect.
Copy the intialization when constructing `TSNEEmbedding` and `PartialTSNEEmbedding` objects. This only happens once, so the memory impact should be minimal.
=> Fix inplace optimization changing init (in some cases)

openTSNE/initialization.py, tests/test_correctness.py, tests/test_different_usages.py, tests/test_tsne.py
A tiny PR that would fix #224, #223, and #180. I am not insisting on any of these changes, but thought I make the PR to make it easier to discuss.
=> Improve PCA and spectral inits

openTSNE/tsne.py, tests/test_different_usages.py, tests/test_tsne.py
Fix #228 and add a corresponding test.
=> Store the last update between optimize() calls

openTSNE/quad_tree.pyx, tests/test_correctness.py
Fixes #223.
The `is_duplicate` function in the BH implementation had a threshold set to 1e-6, likely taken from other implementations, perhaps scikit-learn. This meant that during the EE phase, where everything was squished together, this condition was triggered a lot, meaning BH wasn't splitting up the points into different quadrants, but was pretending it was dealing with a single point. This mean that there were no repulsive forces being applied to the points at all, leading to an increasing collapse of all the points.
I simply changed the threshold for duplicate detection to machine precision, and the issue goes away.
I also copied over the test by @dkobak from #234, but I've also let it run the standard phase. We want to make sure that the embedding isn't collapsed at the end of the …
=> Fix BH collapse

openTSNE/_tsne.pyx, openTSNE/quad_tree.pxd, openTSNE/quad_tree.pyx, tests/test_correctness.py
For data sets with duplicate rows, e.g. titanic, the BH approximation would error out with memory errors as the points in the embedding would be forced too close, and thus the BH splitting would go on seemingly without end.
This was brought about with a recent change where we fixed the collapsing embedding problem. The fix there was to allow BH to make more splits in the space, thus enabling the embeddings to properly expand after the EE phase.
My working fix reverts the old limit to node splitting at 1e-6. However, I leave the duplicate detection limit at machine precision, otherwise we'd run into the same EE collapse issue as before.
This now means that points that are too close together will get grouped into the same BH box. This, however, introduces a new problem. This means that BH …
=> Fix exploding memory problem in BH for duplicate rows

openTSNE/affinity.py
This is a very minor suggestion, but I realized some time ago that in some papers we implement "uniform affinities" slightly differently: not as `(P + P.T) / 2` but as `(P + P.T > 0).astype(float)` where `P` is the kNN adjacency matrix. The only difference is that the former has two possible non-zero values, whereas the latter has only one possible non-zero value, which is kind of neat.
This does not really make much of a different in practice, but I thought it may be nice to implement it in `Uniform()` using `symmetrize="average"` and `symmetrize="or"`, in addition to `symmetrize=True/False` which this class has anyway.
=> Implement binary uniform affinity

setup.py
It seems that in the latest version of `pip`, we can no longer pass in a class into `include_dirs` that eventually resolves into a string. This was previously done because running `setup.py` in a fresh environment would fail as numpy had not yet been installed. Therefore, we used a utility `get_numpy_include` class which would import numpy only when it was called, after numpy was already installed. This is apparently no longer supported.
Related issue: #248
Failing tests in PR #246
This is most likely no longer needed because we now build using `pyproject.toml`, where we can pre-specify the build requirements, which will always be installed before the `setup.py` script is run. Therefore, we no longer need any checks if numpy is installed.
Similarly, the `have_cython` check is no longer …
=> setup.py maintenance

README.rst, azure-pipelines-release.yml, azure-pipelines.yml, setup.py
Wheels for Python 3.12 are missing.
- Updating workflow to build wheels for Python 3.12
- Removing building wheels for Python 3.7 which is already out-of-life
=> Build python 3.12 wheels
