fastTSNE/tsne.py

Fixes #9: Properly handle negative values of the  `n_jobs` parameter in the same way sklearn does.

Properly handle negative values of n_jobs

---

fastTSNE/affinity.py
fastTSNE/nearest_neighbors.py
fastTSNE/tsne.py
tests/test_tsne.py

Fixes #15. Adds random state parameter so we replicate results.

Add scikit-learn style random state parameter

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
.travis.yml
appveyor.yml

- Add github issue and PR templates
- Remove Python 3.5 and under from CI tests

Update build matrix

---

fastTSNE/tsne.py
tests/test_tsne.py

Calls to `optimize` didn't save state and had to start with empty gains, potentially slowing down convergence. This may be problematic for larger data sets.
See https://github.com/pavlin-policar/fastTSNE/issues/7#issuecomment-434116821 for discussion.
Change `gradient_descent` into an object that stores gains.

Change gradient descent to object to keep gains through runs

---

MANIFEST.in

The 3 clause BSD license used in this project requires all copies of the software include a copy of the license.
Includes the `LICENSE` file in sdists.

Include a copy of the license in sdists

---

fastTSNE/affinity.py
tests/test_affinities.py

- Allow changing perplexity list in multiscale affinities.
- Implement multiscale affinities using averaging technique instead of using the multiscale kernel.

Implement averaging multiscale affinities

---

fastTSNE/affinity.py
fastTSNE/tsne.py
setup.py

Docs pt. 1 - fix

---

fastTSNE/affinity.py
fastTSNE/nearest_neighbors.py
fastTSNE/pynndescent/distances.py
fastTSNE/pynndescent/pynndescent_.py
fastTSNE/pynndescent/rp_trees.py
fastTSNE/pynndescent/utils.py
fastTSNE/tsne.py
tests/test_nearest_neighbors.py
tests/test_tsne.py

Running pynndescent multiple times with the same random seed would return different results.
Fix. Cosmetic fixes.

Ensure pynndescent properly handles random_state

---

docs/source/api/callbacks.rst
docs/source/examples/03/03_preserving_global_structure.rst
docs/source/examples/04/04_large_data_sets.rst
docs/source/parameters.rst
docs/source/tsne_algorithm.rst
openTSNE/callbacks.py
openTSNE/tsne.py

Typos in documentation and code.
Correction of typos.

[ENH] Fix typos

---

openTSNE/nearest_neighbors.py

Too hasty, now it wasn't computing the proper number of neighbors.

Revert quickfix for properly calling nndescent

---

setup.py

Wasn't finding FFTW3 headers even if they were available in the conda environment.
Add proper include directories to C compilers.
Also, the installation will now raise an Error if the Python version is too low. Hopefully, this will avoid future confusion about what should and should not work.

Add proper conda/pip include dirs to C compilers

---

openTSNE/nearest_neighbors.py

Numba is a bit slow to load, and if we use exact neighbors, than it's being loaded for no reason.
Only load pynndescent and, consequently, numba, when using approximate neighbors.

Lazily import pynndescent

---

openTSNE/nearest_neighbors.py

Fix pynndescent distances warning

---

openTSNE/affinity.py
openTSNE/nearest_neighbors.py
setup.py

`pynndescent` broke backwards compatibility with v0.4.0
Fixes #98

Update neighbors to be compatible with new pynndescent release

---

docs/requirements-doc.txt
docs/source/conf.py

Fix code not showing up in docs

---

azure-pipelines.yml
benchmarks/macosko.py
openTSNE/affinity.py
openTSNE/initialization.py
openTSNE/nearest_neighbors.py
openTSNE/tsne.py

Fixup verbose messages

---

openTSNE/affinity.py
openTSNE/tsne.py
tests/test_affinities.py
tests/test_tsne.py

Add uniform affinity model

---

openTSNE/nearest_neighbors.py
openTSNE/tsne.py
tests/test_nearest_neighbors.py

Deprecate neighbors_method attribute and replace it with neighbors to
satisfy scikit-learn warnings in repr.

Fixes #139

---

openTSNE/dependencies/annoy/annoylib.h
openTSNE/dependencies/annoy/annoymodule.cc
openTSNE/dependencies/annoy/mman.h
openTSNE/nearest_neighbors.py
setup.py

Update annoy dependency to v1.17. This should be faster than before, as index building now uses multiple cores. https://github.com/spotify/annoy/pull/495

Update to annoy v1.17.0

---

openTSNE/nearest_neighbors.py
tests/test_nearest_neighbors.py

Fixes #146, #145, and updates metrics as per #142.

pynndescent: n_jobs, metrics, verbose

---

azure-pipelines-release.yml

Build wheels for MacOS target 10.6

---

azure-pipelines-release.yml
azure-pipelines.yml
openTSNE/affinity.py
openTSNE/utils.py
tests/test_nearest_neighbors.py
tests/test_tsne.py

Add Python 3.9 to tests and release pipelines.

Add Python 3.9 support

---

openTSNE/tsne.py

Transform was resulting in erratic behaviour when using the clipping to disc.
Also, due to a weird call order that I missed, the clipping wasn't applied to the first transform call on an embedding but was applied later on. This resulted in the first transform working fine, and subsequent calls behaving strangely.
Clipping to circular boundary is now always applied, and there is no strange behaviour anymore.

Fix problem with transform clipping to disc

---

openTSNE/affinity.py

Fix a bug in auto neighbor method choice

---

openTSNE/nearest_neighbors.py
tests/test_nearest_neighbors.py

Fixes #155.
As stated in the code Notes section, this is an extremely inelegant workaround that could potentially cause a lot of confusion. However, something is better than nothing, especially since annoy is used for large data sets, which can take a long time to compute.

Add sketchy workaround to support pickling for annoy

---

openTSNE/tsne.py
tests/test_tsne.py

Fix interpolation grid being created even with BH approximation

---

openTSNE/nearest_neighbors.py
tests/test_different_usages.py

Allow transform with metric="precomputed" using the query as distances

---

README.rst

Add citation for BH algorithm

---

azure-pipelines-release.yml

Provide macos universal2 wheels for apple silicon
Build macos universal2 wheels.

azure-pipelines-release.yml: Build macos universal2 wheels
